pipeline{
    agent any

    environment{
        RELEASE='0.0.1'
    }

    stages{
        // los stage son completamente independientes entre si, y pueden tener su propio agent o environment
        stage('Build'){

            environment{
                LOG_LEVEL='INFO'
            }

            steps{
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}"
            }

        }
        stage('Test'){
            steps{
                // no puedo tener acceso a LOG_LEVEL
                echo "Testing, I can see release ${RELEASE} with log level ${LOG_LEVEL}"
            }
        }
    }
}