pipeline{
    agent any

    environment{
        // sh es un plugin que nos permite hacer varias cosas
        // nos movemos como si estuvieramos en JENKINS-SESSION2 poruqe es la raiz del repositorio
        VERSION=sh([script: 'cd ./01/solution && npm rn env | grep "npm_package_version', returnStdout: true]).trim()
        VERSION_RC= "rc.2"
    }

    stages{
        // los stage son completamente independientes entre si, y pueden tener su propio agent o environment
        stage('Audit tools'){

            steps{
                sh '''
                    git version
                    docker version
                    node --version
                    npm version
                '''
            }

        }
        stage('Build'){
            steps{
                // dir es un plugin que nos permite cambiar de directorio
                // nos movemos como si estuvieramos en JENKINS-SESSION2 poruqe es la raiz del repositorio
                dir('./01/solucion'){
                    echo "Building version ${VERSION} with suffix: ${VERSION_RC}"
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }
        stage('Unit Test'){
            
            steps{
                dir('./01/solution/src'){
                    sh '''
                        npm test
                    '''
                }
            }
        }
    }

}