pipeline{

    agent any
    // variable global que se destruye cuando termina
    environment{
        DEMO='1.3'
    }

    stages{
        stage('stage-1'){
            steps{
                // BUILD_NUMBERS es una variable de Jenkins
                echo "this is build number $BUILD_NUMBER OF $DEMO"
                // desde test.sh puedo usar la variable DEMO
                sh '''
                    echo "Using a multi shell steps"
                    chmod +x test.sh
                    ./test.sh
                '''
            }
        }
    }
}