pipeline{
    agent any

    environment{
        RELEASE='0.0.1'
    }

    stages{
        // los stage son completamente independientes entre si, y pueden tener su propio agent o environment
        stage('Build'){

            environment{
                LOG_LEVEL='INFO'
            }

            parallel{
                stage('Linux'){
                    steps{
                        echo "Releasing ${RELEASE} for ${STAGE_NAME}"
                    }
                }
                stage('Windows'){
                    steps{
                        echo "Releasing ${RELEASE} for ${STAGE_NAME}"
                    }
                }
            }

            // steps{
            //     echo "Building release ${RELEASE} with log level ${LOG_LEVEL}"
            // }

        }
        stage('Test'){
            steps{
                // no puedo tener acceso a LOG_LEVEL
                echo "Testing release"
            }
        }
        stage('Deploy'){
            input{
                message 'Deploy?'
                ok 'Do it!'
                parameters{
                    string(name: 'TARGET_ENVIRONMENT', defaultValue:'PROD', description: "Target deployment environment")
                }
            }
            steps{
                echo "Deploying release ${RELEASE} to env ${TARGET_ENVIRONMENT}"
            }
        }
    }

    // despues de los stages se ejecutara el post
    post{
        always{
            echo "Prints success or failiure"
        }
    }
}